/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardGuildIdRouteImport } from './routes/dashboard.$guildId'
import { Route as DashboardGuildIdIndexRouteImport } from './routes/dashboard.$guildId.index'
import { Route as DashboardGuildIdQuestsRouteImport } from './routes/dashboard.$guildId.quests'
import { Route as DashboardGuildIdPetRouteImport } from './routes/dashboard.$guildId.pet'
import { Route as DashboardGuildIdModerationRouteImport } from './routes/dashboard.$guildId.moderation'
import { Route as DashboardGuildIdLevelingRouteImport } from './routes/dashboard.$guildId.leveling'
import { Route as DashboardGuildIdKarmaRouteImport } from './routes/dashboard.$guildId.karma'
import { Route as DashboardGuildIdCurrencyRouteImport } from './routes/dashboard.$guildId.currency'
import { Route as DashboardGuildIdCommandsRouteImport } from './routes/dashboard.$guildId.commands'
import { Route as DashboardGuildIdBadgesRouteImport } from './routes/dashboard.$guildId.badges'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuildIdRoute = DashboardGuildIdRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuildIdIndexRoute = DashboardGuildIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdQuestsRoute = DashboardGuildIdQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdPetRoute = DashboardGuildIdPetRouteImport.update({
  id: '/pet',
  path: '/pet',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdModerationRoute =
  DashboardGuildIdModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdLevelingRoute =
  DashboardGuildIdLevelingRouteImport.update({
    id: '/leveling',
    path: '/leveling',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdKarmaRoute = DashboardGuildIdKarmaRouteImport.update({
  id: '/karma',
  path: '/karma',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)
const DashboardGuildIdCurrencyRoute =
  DashboardGuildIdCurrencyRouteImport.update({
    id: '/currency',
    path: '/currency',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdCommandsRoute =
  DashboardGuildIdCommandsRouteImport.update({
    id: '/commands',
    path: '/commands',
    getParentRoute: () => DashboardGuildIdRoute,
  } as any)
const DashboardGuildIdBadgesRoute = DashboardGuildIdBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => DashboardGuildIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$guildId/badges': typeof DashboardGuildIdBadgesRoute
  '/dashboard/$guildId/commands': typeof DashboardGuildIdCommandsRoute
  '/dashboard/$guildId/currency': typeof DashboardGuildIdCurrencyRoute
  '/dashboard/$guildId/karma': typeof DashboardGuildIdKarmaRoute
  '/dashboard/$guildId/leveling': typeof DashboardGuildIdLevelingRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/pet': typeof DashboardGuildIdPetRoute
  '/dashboard/$guildId/quests': typeof DashboardGuildIdQuestsRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$guildId/badges': typeof DashboardGuildIdBadgesRoute
  '/dashboard/$guildId/commands': typeof DashboardGuildIdCommandsRoute
  '/dashboard/$guildId/currency': typeof DashboardGuildIdCurrencyRoute
  '/dashboard/$guildId/karma': typeof DashboardGuildIdKarmaRoute
  '/dashboard/$guildId/leveling': typeof DashboardGuildIdLevelingRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/pet': typeof DashboardGuildIdPetRoute
  '/dashboard/$guildId/quests': typeof DashboardGuildIdQuestsRoute
  '/dashboard/$guildId': typeof DashboardGuildIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$guildId': typeof DashboardGuildIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$guildId/badges': typeof DashboardGuildIdBadgesRoute
  '/dashboard/$guildId/commands': typeof DashboardGuildIdCommandsRoute
  '/dashboard/$guildId/currency': typeof DashboardGuildIdCurrencyRoute
  '/dashboard/$guildId/karma': typeof DashboardGuildIdKarmaRoute
  '/dashboard/$guildId/leveling': typeof DashboardGuildIdLevelingRoute
  '/dashboard/$guildId/moderation': typeof DashboardGuildIdModerationRoute
  '/dashboard/$guildId/pet': typeof DashboardGuildIdPetRoute
  '/dashboard/$guildId/quests': typeof DashboardGuildIdQuestsRoute
  '/dashboard/$guildId/': typeof DashboardGuildIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/$guildId'
    | '/dashboard/'
    | '/dashboard/$guildId/badges'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/currency'
    | '/dashboard/$guildId/karma'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/pet'
    | '/dashboard/$guildId/quests'
    | '/dashboard/$guildId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/$guildId/badges'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/currency'
    | '/dashboard/$guildId/karma'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/pet'
    | '/dashboard/$guildId/quests'
    | '/dashboard/$guildId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/$guildId'
    | '/dashboard/'
    | '/dashboard/$guildId/badges'
    | '/dashboard/$guildId/commands'
    | '/dashboard/$guildId/currency'
    | '/dashboard/$guildId/karma'
    | '/dashboard/$guildId/leveling'
    | '/dashboard/$guildId/moderation'
    | '/dashboard/$guildId/pet'
    | '/dashboard/$guildId/quests'
    | '/dashboard/$guildId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$guildId': {
      id: '/dashboard/$guildId'
      path: '/$guildId'
      fullPath: '/dashboard/$guildId'
      preLoaderRoute: typeof DashboardGuildIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$guildId/': {
      id: '/dashboard/$guildId/'
      path: '/'
      fullPath: '/dashboard/$guildId/'
      preLoaderRoute: typeof DashboardGuildIdIndexRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/quests': {
      id: '/dashboard/$guildId/quests'
      path: '/quests'
      fullPath: '/dashboard/$guildId/quests'
      preLoaderRoute: typeof DashboardGuildIdQuestsRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/pet': {
      id: '/dashboard/$guildId/pet'
      path: '/pet'
      fullPath: '/dashboard/$guildId/pet'
      preLoaderRoute: typeof DashboardGuildIdPetRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/moderation': {
      id: '/dashboard/$guildId/moderation'
      path: '/moderation'
      fullPath: '/dashboard/$guildId/moderation'
      preLoaderRoute: typeof DashboardGuildIdModerationRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/leveling': {
      id: '/dashboard/$guildId/leveling'
      path: '/leveling'
      fullPath: '/dashboard/$guildId/leveling'
      preLoaderRoute: typeof DashboardGuildIdLevelingRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/karma': {
      id: '/dashboard/$guildId/karma'
      path: '/karma'
      fullPath: '/dashboard/$guildId/karma'
      preLoaderRoute: typeof DashboardGuildIdKarmaRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/currency': {
      id: '/dashboard/$guildId/currency'
      path: '/currency'
      fullPath: '/dashboard/$guildId/currency'
      preLoaderRoute: typeof DashboardGuildIdCurrencyRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/commands': {
      id: '/dashboard/$guildId/commands'
      path: '/commands'
      fullPath: '/dashboard/$guildId/commands'
      preLoaderRoute: typeof DashboardGuildIdCommandsRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
    '/dashboard/$guildId/badges': {
      id: '/dashboard/$guildId/badges'
      path: '/badges'
      fullPath: '/dashboard/$guildId/badges'
      preLoaderRoute: typeof DashboardGuildIdBadgesRouteImport
      parentRoute: typeof DashboardGuildIdRoute
    }
  }
}

interface DashboardGuildIdRouteChildren {
  DashboardGuildIdBadgesRoute: typeof DashboardGuildIdBadgesRoute
  DashboardGuildIdCommandsRoute: typeof DashboardGuildIdCommandsRoute
  DashboardGuildIdCurrencyRoute: typeof DashboardGuildIdCurrencyRoute
  DashboardGuildIdKarmaRoute: typeof DashboardGuildIdKarmaRoute
  DashboardGuildIdLevelingRoute: typeof DashboardGuildIdLevelingRoute
  DashboardGuildIdModerationRoute: typeof DashboardGuildIdModerationRoute
  DashboardGuildIdPetRoute: typeof DashboardGuildIdPetRoute
  DashboardGuildIdQuestsRoute: typeof DashboardGuildIdQuestsRoute
  DashboardGuildIdIndexRoute: typeof DashboardGuildIdIndexRoute
}

const DashboardGuildIdRouteChildren: DashboardGuildIdRouteChildren = {
  DashboardGuildIdBadgesRoute: DashboardGuildIdBadgesRoute,
  DashboardGuildIdCommandsRoute: DashboardGuildIdCommandsRoute,
  DashboardGuildIdCurrencyRoute: DashboardGuildIdCurrencyRoute,
  DashboardGuildIdKarmaRoute: DashboardGuildIdKarmaRoute,
  DashboardGuildIdLevelingRoute: DashboardGuildIdLevelingRoute,
  DashboardGuildIdModerationRoute: DashboardGuildIdModerationRoute,
  DashboardGuildIdPetRoute: DashboardGuildIdPetRoute,
  DashboardGuildIdQuestsRoute: DashboardGuildIdQuestsRoute,
  DashboardGuildIdIndexRoute: DashboardGuildIdIndexRoute,
}

const DashboardGuildIdRouteWithChildren =
  DashboardGuildIdRoute._addFileChildren(DashboardGuildIdRouteChildren)

interface DashboardRouteChildren {
  DashboardGuildIdRoute: typeof DashboardGuildIdRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGuildIdRoute: DashboardGuildIdRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
